```{r}
pos<-replicate(1000,sum(runif(16,-1,-1)))
hist(pos)
plot(density(pos))
```

```{r}
w<-6;n<-9
p_grid<-seq(from=0,to=1,length.out=100)
posterior<-dbinom(w,n,p_grid)*dunif(p_grid,0,1)
posterior<-posterior/sum(posterior)
```

```{r}
library(rethinking)
data(Howell1)
d<-Howell1
```

```{r}
str(d)
```

```{r}
precis(d)
```

```{r}
d2<-d[d$age>=18,]
dens(d2$height)
```

```{r}
curve(dnorm(x,178,20),from=100,to=250)
```

```{r}
curve(dunif(x,0,50),from=-10,to=60)
```

```{r}
sample_mu<-rnorm(1e4,178,20)
sample_sigma<-runif(1e4,0,50)
prior_h<-rnorm(1e4,sample_mu,sample_sigma)
dens(prior_h)
```

```{r}
sample_mu<-rnorm(1e4,178,100)
prior_h<-rnorm(1e4,sample_mu,sample_sigma)
dens(prior_h)
```

```{r}
mu.list<-seq(from=150,to=160,length.out=100)
sigma.list<-seq(from=7,to=9,length.out=100)
post<-expand.grid(mu=mu.list,sigma=sigma.list)
post$LL<-sapply(1:nrow(post),function(i) sum(
  dnorm(d2$height, post$mu[i], post$sigma[i],log=TRUE)
))
post$prod<-post$LL+dnorm(post$mu, 178,20,TRUE)+dunif(post$sigma,0,50,TRUE)
post$prob<-exp(post$prod-max(post$prod))

```

```{r}
contour_xyz(post$mu,post$sigma,post$prob)
```

```{r}
image_xyz(post$mu,post$sigma,post$prob)
```

```{r}
sample.rows<-sample(1:nrow(post),size=1e4,replace=TRUE,prob=post$prob)
sample.mu<-post$mu[sample.rows]
sample.sigma<-post$sigma[sample.rows]
```

```{r}
plot(sample.mu,sample.sigma,cex=0.5,pch=16,col=col.alpha(rangi2,0.1))
```

```{r}
dens(sample.mu)
dens(sample.sigma)
```

```{r}
PI(sample.mu)
PI(sample.sigma)
```

```{r}
d3<-sample(d$height,size=20)
mu.list<-seq(from=150,to=170,length.out=200)
sigma.list<-seq(from=4,to=20,length.out=200)
post2<-expand.grid(mu=mu.list,sigma=sigma.list)
post2$LL<-sapply(1:nrow(post2), function(i)
  sum(dnorm(d3,mean=post2$mu[i],sd=post2$sigma[i],log=TRUE))  )
post2$prod<-post2$LL+dnorm(post2$mu,178,20,TRUE)+dunif(post2$sigma,0,50,TRUE)
post2$prob<-exp(post2$prod-max(post2$prod))
sample2.rows<-sample(1:nrow(post2),size=1e4,replace=TRUE,prob=post2$prob)
sample2.mu<-post2$mu[sample2.rows]
sample2.sigma<-post2$sigma[sample2.rows]
plot(sample2.mu,sample2.sigma,cex=0.5,col=col.alpha(rangi2,0.1),xlab="mu",ylab="sigma",pch=16)
```

```{r}
dens(sample2.sigma,norm.comp=TRUE)
```

```{r}
library(rethinking)
data(Howell1)
d<-Howell1
d2<-d[d$age>=18,]
```

```{r}
flist<-alist(
  height~dnorm(mu,sigma),
  mu~dnorm(178,20),
  sigma~dunif(0,50)
)
```

```{r}
m4.1<-quap(flist,data=d2)
```

```{r}
precis(m4.1)
```

```{r}
vcov(m4.1)
```

```{r}
diag(vcov(m4.1))
cov2cor(vcov(m4.1))
```

```{r}
post<-extract.samples(m4.1,n=1e4)
head(post)
```

```{r}
precis(post)
```

```{r}
plot(post)
```

## 4.4 Linear Prediction

```{r}
plot(d2$height~d2$weight)
```

```{r}
set.seed(2971)
N<-100
a<-rnorm(N,178,20)
b<-rnorm(N,0,10)

```

```{r}
plot(NULL,xlim=range(d2$weight),ylim=c(-100,400),xlab="weight",ylab="height")
abline(h=0,lty=2)
abline(h=272,lty=1,lwd=0.5)
mtext("b~dnorm(0,10")
xbar<-mean(d2$weight)
for (i in 1:N) curve(a[i]+b[i]*(x-xbar), from=min(d2$weight),to=max(d2$weight), add=TRUE, col=col.alpha("black",0.2))
```

```{r}
b<-rlnorm(1e4,0,1)
dens(b,xlim=c(0,5),adj=0.1)
```

```{r}
set.seed(2971)
N<-100
a<-rnorm(N,178,20)
b<-rlnorm(N,0,1)

plot(NULL,xlim=range(d2$weight),ylim=c(-100,400),xlab="weight",ylab="height")
abline(h=0,lty=2)
abline(h=272,lty=1,lwd=0.5)
mtext("b~dnorm(0,10")
xbar<-mean(d2$weight)
for (i in 1:N) curve(a[i]+b[i]*(x-xbar), from=min(d2$weight),to=max(d2$weight), add=TRUE, col=col.alpha("black",0.2))
```

```{r}
library(rethinking)
data(Howell1)
d<-Howell1
d2<-d[d$age>=18,]

# define the avg weight
xbar<-mean(d2$weight)

# fit model
m4.3<-quap(
  alist(
    height~dnorm(mu,sigma),
    mu<-a+b*(weight-xbar),
    a~dnorm(178,20),
    b~dlnorm(0,1),
    sigma~dunif(0,50)
  ), data=d2
)

```

```{r}
precis(m4.3)
```

```{r}
round(vcov(m4.3),3)
```

```{r}
plot(height~weight,data=d2,col=rangi2)
post<-extract.samples(m4.3)
a_map<-mean(post$a)
b_map<-mean(post$b)
curve(a_map+b_map*(x-xbar),add=TRUE)
```

```{r}
post<-extract.samples(m4.3)
post[1:5,]
```

```{r}
N<-10
dN<-d2[1:N,]
mN<-quap(
  alist(
    height~dnorm(mu,sigma),
    mu<-a+b*(weight-mean(weight)),
    a~dnorm(178,20),
    b~dlnorm(0,1),
    sigma~dunif(0,50)
  ), data=dN
)
```

```{r}
# extract 20 samples from the posterior
post<-extract.samples(mN,n=20)

# display raw data and sample size
plot(dN$weight, dN$height, xlim=range(d2$weight),ylim=range(d2$height), col=rangi2, xlab="weight",ylab="height")
mtext(concat("N=",N))
# plot the lines, with transparency
for (i in 1:20)
  curve(post$a[i]+post$b[i]*(x-mean(dN$weight)),col=col.alpha("black",0.3),add=TRUE)
  
```

```{r}
post<-extract.samples(m4.3)
mu_at_50<-post$a+post$b*(50-xbar)
dens(mu_at_50,col=rangi2,lwd=2,xlab="mu|weight=50")
```

```{r}
PI(mu_at_50,prob=0.89)
```

```{r}
mu<-link(m4.3)
str(mu)
```

```{r}
weight.seq<-seq(from=25,to=70,by=1)

mu<-link(m4.3, data=data.frame(weight=weight.seq))
str(mu)
```

```{r}
plot(height~weight,d2,type="n")

for (i in 1:100)
  points(weight.seq,mu[i,],pch=16,col=col.alpha(rangi2,0.1))
```

```{r}
mu.mean<-apply(mu,2,mean)
mu.PI<-apply(mu,2,PI,prob=0.89)
(mu.mean)
```

```{r}
(mu.PI)
```

```{r}
plot(height~weight,data=d2,col=col.alpha(rangi2,0.5))
lines(weight.seq,mu.mean)
shade(mu.PI,weight.seq)
```

```{r}
sim.height<-sim(m4.3,data=list(weight=weight.seq))
str(sim.height)
```

```{r}
height.PI<-apply(sim.height,2,PI,prob=0.98)
plot(height~weight,d2,col=col.alpha(rangi2,0.5))

lines(weight.seq,mu.mean)

shade(height.PI,weight.seq)
```

## Curves From Lines

```{r}
d$weight_s<-(d$weight-mean(d$weight))/sd(d$weight)
d$weight_s2<-d$weight_s^2
m4.5<-quap(
  alist(
    height~dnorm(mu,sigma),
    mu<-a+b1*weight_s+b2*(weight_s2),
    a~dnorm(178,20),
    b1~dlnorm(0,1),
    b2~dnorm(0,1),
    sigma~dunif(0,50)
  ),data=d
)
```

```{r}
precis(m4.5)
```

```{r}
weight.seq<-seq(from=-2.2,to=2,length.out=30)
pred_dat<-list(weight_s=weight.seq,weight_s2=weight.seq^2)
mu<-link(m4.5,data=pred_dat)
mu.mean<-apply(mu,2,mean)
mu.PI<-apply(mu,2,PI,prob=0.89)
sim.height<-sim(m4.5,data=pred_dat)
height.PI<-apply(sim.height,2,PI,prob=0.89)
```

```{r}
plot(height~weight_s,d,col=col.alpha(rangi2,0.5))
lines(weight.seq,mu.mean)
shade(mu.PI,weight.seq)
shade(height.PI,weight.seq)
```

```{r}
library(rethinking)
data(cherry_blossoms)
d<-cherry_blossoms
precis(d)
```

```{r}
plot(d$temp)
```

```{r}
d2<-d[complete.cases(d$temp),]
num_knots<-15
knot_list<-quantile(d2$year,prob=seq(0,1,length.out=num_knots))
```

```{r}
library(splines)
B<-bs(d2$year,knots=knot_list[-c(1,num_knots)], degree=3,intercept=TRUE)
```

```{r}
plot(NULL,xlim=range(d2$year),ylim=c(0,1),xlab="year",ylab="basis value")
for (i in 1:ncol(B)) lines(d2$year, B[,i])
```

```{r}
m4.7<-quap(
  alist(
    T~dnorm(mu,sigma),
    mu<-a+B%*%w,
    a~dnorm(6,10),
    w~dnorm(0,1),
    sigma~dexp(1)
  ),
  data=list(T=d2$temp, B=B),
  start=list(w=rep(0,ncol(B)))
)
```

```{r}
post<-extract.samples(m4.7)
w<-apply(post$w,2, mean)
plot(NULL,xlim=range(d2$year),ylim=c(-2,2),xlab="year",ylab="basis*weight")
for (i in 1:ncol(B)) lines(d2$year,w[i]*B[,i])
```

```{r}
mu<-link(m4.7)
mu_PI<-apply(mu,2,PI,0.97)
plot(d2$year,d2$temp,col=col.alpha(rangi2,0.3),pch=16)
shade(mu_PI,d2$year,col=col.alpha("black",0.5))
```
