## Excerise 2

```{r}
p_grid<-seq(from=0,to=1,length.out=20)
p_prior<-rep(1,20)

likelihood<-dbinom(3,size=3,prob=p_grid)
unstd.posterior<-likelihood*p_prior

posterior<-unstd.posterior/sum(unstd.posterior)

plot(p_grid, posterior, type="b", xlab="probability of water", ylab="posterior probability")
mtext("20 points")
```

```{r}
p_grid<-seq(from=0,to=1,length.out=20)
p_prior<-rep(1,20)

likelihood<-dbinom(3,size=4,prob=p_grid)
unstd.posterior<-likelihood*p_prior

posterior<-unstd.posterior/sum(unstd.posterior)

plot(p_grid, posterior, type="b", xlab="probability of water", ylab="posterior probability")
mtext("20 points")
```

```{r}
p_grid<-seq(from=0,to=1,length.out=20)
p_prior<-rep(1,20)

likelihood<-dbinom(5,size=7,prob=p_grid)
unstd.posterior<-likelihood*p_prior

posterior<-unstd.posterior/sum(unstd.posterior)

plot(p_grid, posterior, type="b", xlab="probability of water", ylab="posterior probability")
mtext("20 points")
```

## Exercise 3

```{r}
p_grid<-seq(from=0,to=1,length.out=20)
p_prior <- ifelse( p_grid < 0.5 , 0 , 2 )

likelihood<-dbinom(3,size=3,prob=p_grid)
unstd.posterior<-likelihood*p_prior

posterior<-unstd.posterior/sum(unstd.posterior)

plot(p_grid, posterior, type="b", xlab="probability of water", ylab="posterior probability")
mtext("20 points")

```

```{r}
p_grid<-seq(from=0,to=1,length.out=10)
p_prior <- ifelse( p_grid < 0.5 , 0 , 2 )

likelihood<-dbinom(3,size=4,prob=p_grid)
unstd.posterior<-likelihood*p_prior

posterior<-unstd.posterior/sum(unstd.posterior)

plot(p_grid, posterior, type="b", xlab="probability of water", ylab="posterior probability")
mtext("20 points")
```

```{r}
p_grid<-seq(from=0,to=1,length.out=20)
p_prior <- ifelse( p_grid < 0.5 , 0 , 2 )

likelihood<-dbinom(5,size=7,prob=p_grid)
unstd.posterior<-likelihood*p_prior

posterior<-unstd.posterior/sum(unstd.posterior)

plot(p_grid, posterior, type="b", xlab="probability of water", ylab="posterior probability")
mtext("20 points")
```
