## Spurious association

```{r}
library(rethinking)
data("WaffleDivorce")
d<-WaffleDivorce

d$A<-scale(d$MedianAgeMarriage)
d$D<-scale(d$Divorce)
```

```{r}
sd(d$MedianAgeMarriage)
```

```{r}
m5.1<-quap(
  alist(
    D~dnorm(mu,sigma),
    mu<-a+bA*A,
    a~dnorm(0,0.2),
    bA~dnorm(0,0.5),
    sigma~dexp(1)
  ),data=d
)
```

```{r}
set.seed(10)
prior<-extract.prior((m5.1))
mu<-link(m5.1,post=prior,data=list(A=c(-2,2)))
plot(NULL,xlim=c(-2,2),ylim=c(-2,2))
for (i in 1:50) lines(c(-2,2), mu[i,], col=col.alpha("black",0.4))
```

```{r}
A_seq<-seq(from=-3,to=3.2,length.out=30)
mu<-link(m5.1,data=list(A=A_seq))
mu.mean<-apply(mu,2,mean)
mu.PI<-apply(mu,2,PI)

plot(D~A, data=d, col=rangi2)
lines(A_seq,mu.mean,lwd=2)
shade(mu.PI,A_seq)
```

```{r}
d$M<-scale(d$Marriage)
m5.2<-quap(
  alist(
    D~dnorm(mu,sigma),
    mu<-a+bM*M,
    a~dnorm(0,0.2),
    bM~dnorm(0,0.5),
    sigma~dexp(1)
  ),data=d
)

M_seq<-seq(from=-3,to=3.2,length.out=30)
mu<-link(m5.2,data=list(M=M_seq))
mu.mean<-apply(mu,2,mean)
mu.PI<-apply(mu,2,PI)

plot(D~M, data=d, col=rangi2)
lines(M_seq,mu.mean,lwd=2)
shade(mu.PI,A_seq)
```

```{r}
library(dagitty)
DMA_dag2<-dagitty('dag{D<-A->M}')
impliedConditionalIndependencies(DMA_dag2)
```

```{r}
DMA_dag1<-dagitty('dag{D<-A->M->D}')
impliedConditionalIndependencies(DMA_dag1)
```

```{r}
m5.3<-quap(
  alist(
    D~dnorm(mu,sigma),
    mu<-a+bM*M+bA*A,
    a~dnorm(0,0.2),
    bM~dnorm(0,0.5),
    bA~dnorm(0,0.5),
    sigma~dexp(1)
  ), data=d
)
precis(m5.3)
```

```{r}
plot(coeftab(m5.1,m5.2,m5.3),par=c("bA","bM"))
```

```{r}
m5.4<-quap(
  alist(
    M~dnorm(mu,sigma),
    mu<-a+bAM*A,
    a~dnorm(0,0.2),
    bAM~dnorm(0,0.5),
    sigma~dexp(1)
  ),data=d
)
```

```{r}
mu<-link(m5.4)
mu_mean<-apply(mu,2,mean)
mu_resid<-d$M-mu_mean
```

```{r}
mu<-link(m5.3)

#summarize samples accross cases
mu_mean<-apply(mu,2,mean)
mu_PI<-apply(mu,2,PI)

# simulate observations
D_sim<-sim(m5.3,n=1e4)
D_PI<-apply(D_sim,2,PI)
```

```{r}
plot(mu_mean~d$D,col=rangi2,ylim=range(mu_PI),xlab="Observed divorce",ylab="Predicted divorce")
abline(a=0,b=1,lty=2)
for (i in 1:nrow(d)) lines(rep(d$D[i],2),mu_PI[,i],col=rangi2)
```

## Masked Relationship

```{r}
library(rethinking)
data(milk)
d<-milk
str(d)
```

```{r}
d$K<-scale(d$kcal.per.g)
d$N<-scale(d$neocortex.perc)
d$M<-scale(log(d$mass))
```

```{r}
m5.5_draft<-quap(
  alist(
    K~dnorm(mu,sigma),
    mu<-a+bN*N,
    a~dnorm(0,1),
    bN~dnorm(0,1),
    sigma~dexp(1)
  ),data=d
)
```

```{r}
d$neocortex.perc
```

```{r}
dcc<-d[complete.cases(d$K,d$N,d$M),]
```

```{r}
m5.5_draft<-quap(
  alist(
    K~dnorm(mu,sigma),
    mu<-a+bN*N,
    a~dnorm(0,1),
    bN~dnorm(0,1),
    sigma~dexp(1)
  ),data=dcc
)
```

```{r}
prior<-extract.prior(m5.5_draft)
xseq<-c(-2,2)
mu<-link(m5.5_draft,post=prior,data=list(N=xseq))
plot(NULL,xlim=xseq,ylim=xseq)
for (i in 1:50) lines(xseq,mu[i,],col=col.alpha("black",0.3))
```

```{r}
m5.5<-quap(
  alist(
    K~dnorm(mu,sigma),
    mu<-a+bN*N,
    a~dnorm(0,0.2),
    bN~dnorm(0,0.5),
    sigma~dexp(1)
  ),data=dcc
)
```

```{r}
precis(m5.5)
```

```{r}
xseq<-seq(from=min(dcc$N)-0.15,to=max(dcc$N)+0.15,length.out=30)
mu<-link(m5.5,data=list(N=xseq))
mu_mean<-apply(mu,2,mean)
mu_PI<-apply(mu,2,PI)
plot(K~N,data=dcc)
lines(xseq,mu_mean,lwd=2)
shade(mu_PI,xseq)

```

```{r}
m5.6<-quap(
  alist(
    K~dnorm(mu,sigma),
    mu<-a+bM*M,
    a~dnorm(0,0.2),
    bM~dnorm(0,0.5),
    sigma~dexp(1)
  ),data=dcc
)
precis(m5.6)
```

```{r}
xseq<-seq(from=min(dcc$M)-0.15,to=max(dcc$M)+0.15,length.out=30)
mu<-link(m5.6,data=list(M=xseq))
mu_mean<-apply(mu,2,mean)
mu_PI<-apply(mu,2,PI)
plot(K~M,data=dcc)
lines(xseq,mu_mean,lwd=2)
shade(mu_PI,xseq)
```

```{r}
m5.7<-quap(
  alist(
    K~dnorm(mu,sigma),
    mu<-a+bN*N+bM*M,
    a~dnorm(0,0.2),
    bN~dnorm(0,0.5),
    bM~dnorm(0,0.5),
    sigma~dexp(1)
  ),data=dcc
)
precis(m5.7)
```

```{r}
plot(coeftab(m5.5,m5.6,m5.7),pars=c("bM","bN"))
```

```{r}
pairs(~K+M+N,dcc)
```

```{r}
xseq<-seq(from=min(dcc$M-0.15),to=max(dcc$M)+0.15, length.out=30)
mu<-link(m5.7,data=data.frame(M=xseq,N=0))
mu_mean<-apply(mu,2,mean)
mu_PI<-apply(mu,2,PI)
plot(NULL,xlim=range(dcc$M),ylim=range(dcc$K),xlab="log body mass (std)", ylab="kilcal per g (std)")
mtext("Counterfactual holding N=0")
lines(xseq,mu_mean,lwd=2)
shade(mu_PI,xseq)
```

```{r}
xseq<-seq(from=min(dcc$N-0.15),to=max(dcc$N)+0.15, length.out=30)
mu<-link(m5.7,data=data.frame(N=xseq,M=0))
mu_mean<-apply(mu,2,mean)
mu_PI<-apply(mu,2,PI)
plot(NULL,xlim=range(dcc$N),ylim=range(dcc$K),xlab="neocortex percent (std)", ylab="kilcal per g (std)")
mtext("Counterfactual holding M=0")
lines(xseq,mu_mean,lwd=2)
shade(mu_PI,xseq)
```

```{r}
# M->K<-N
# M->N
n<-100
M<-rnorm(n)
N<-rnorm(n,M)
K<-rnorm(n,N-M)
d_sim<-data.frame(K=K,N=N,M=M)
```

## Categorical variables

```{r}
data(Howell1)
d<-Howell1
str(d)
```

```{r}
mu_female<-rnorm(1e4,178,20)
mu_male<-rnorm(1e4,178,20)+rnorm(1e4,0,10)
precis(data.frame(mu_female,mu_male))
```

```{r}
d$sex<-ifelse(d$male==1,2,1)
str(d$sex)
```

```{r}
m5.8<-quap(
  alist(
    height ~ dnorm( mu , sigma ) ,
    mu <- a[sex] ,
    a[sex] ~ dnorm( 178 , 20 ) ,
    sigma~dunif(0,50)
  ), data=d
)
precis(m5.8,depth=2)
```

```{r}
post<-extract.samples(m5.8)
post$diff_fm<-post$a[,1]-post$a[,2]
precis(post,depth=2)
```

```{r}
data(milk)
d<-milk
unique(d$clade)
```

```{r}
d$clade_id<-as.integer(d$clade)
```

```{r}
d$K<-scale(d$kcal.per.g)
m5.9<-quap(
  alist(
    K~dnorm(mu,sigma),
    mu<-a[clade_id],
    a[clade_id]~dnorm(0,0.5),
    sigma~dexp(1)
  ),data=d
)
labels<-paste("a[",1:4,"]:",levels(d$clade),sep="")
plot(precis(m5.9,depth=2,pars="a"),labels=labels,xlab="expected kcal (std)")
```

```{r}
set.seed(63)
d$house<-sample(rep(1:4,each=8),size=nrow(d))
m5.10<-quap(
  alist(
    K~dnorm(mu,sigma),
    mu<-a[clade_id]+h[house],
    a[clade_id]~dnorm(0,0.5),
    h[house]~dnorm(0,0.5),
    sigma~dexp(1)
  ),data=d
)

post<-extract.samples(m5.10)
precis(post,depth=2)
```
